### ISSUE TITLE
JUnit failures without type or message will be skipped

### ISSUE THREAD

**Issue by Suuirad** [tomasbjerre/violations-lib#100]
The JUnit parser skips all failures wich doesn't have a message or type. 

`if (message == null) {
     continue;
 }`

I know this was inserted in a previouse commit, but in some cases failures will be generated without message and type and it would be useful to get them noticed anyway.

**Comment by tomasbjerre** [comment]
Do you have an example report?

**Comment by Suuirad** [comment]
```
<?xml version='1.0' encoding='UTF-8' ?>
      <testsuite id="codereview.cobol.analysisProvider" name="COBOL Code Review" tests="1" failures="1" time="0.001">
         <testcase id="codereview.cobol.rules.ProgramIdRule" name="Use a program name that matches the source file name" time="0.001">
            <failure>
                WARNING: Use a program name that matches the source file name
                Category: COBOL Code Review – Naming Conventions
                File: /project/PROGRAM.cbl
                Line: 2
      </failure>
    </testcase>
  </testsuite>
```

**Comment by tomasbjerre** [comment]
Did you try the xml-report also?
https://www.ibm.com/support/knowledgecenter/SSQ2R2_9.1.1/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_exportresults.html

It is probably easier to support.

**Comment by Suuirad** [comment]
We are using Jenkins with the Warning NG Plugin. But our JUnit test results, which are in xml doesnt have a failure type or message, so they didn't get noticed by the JUnitParser.

**Comment by tomasbjerre** [comment]
Yes. You supplied an example from *COBOL Code Review*. That tool can also output an XML-format. I suggest supporting that format as it is easier to parse. I would need an example of that format.

**Comment by Suuirad** [comment]
Ok, sorry for the confusion, but i dont using this tool, i just got the example from there. Im using gradle with junit. Here an example report of our project

```
<?xml version='1.0' encoding='UTF-8' ?>
<testsuite name="my.company.MainActivityTest" tests="1" failures="1" errors="0" skipped="0" time="66.551" timestamp="2020-09-04T08:53:58" hostname="localhost">
  <properties>
    <property name="device" value="ATU-L21 - 8.0.0" />
    <property name="flavor" value="" />
    <property name="project" value="app" />
  </properties>
  <testcase name="openAppInfoTest" classname="my.company.MainActivityTest" time="66.529">
    <failure>androidx.test.espresso.AppNotIdleException: Looped for 3838 iterations over 60 SECONDS. The following Idle Conditions failed .
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1556)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:88)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:51)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:312)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:173)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:114)
at my.company.MainActivityTest.openAppInfoTest(MainActivityTest.java:113)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2119)
</failure>
  </testcase>
</testsuite>
```

**Comment by tomasbjerre** [comment]
Releasing a fix now!
