### ISSUE TITLE
CSSLint rollup output causes parsing error

### ISSUE THREAD

**Issue by mike10010100** [tomasbjerre/violations-lib#11]
Example CSSLint output:

...normal csslint file...
```
<csslint>
<file name="foo/bar/style.css>
<issue evidence="" reason="Too many !important declarations (38), try to use less than 10 to avoid specificity issues." severity="warning"/>
<issue evidence="" reason="Too many font-size declarations (35), abstraction needed." severity="warning"/>
<issue evidence="" reason="You have 5 h1s, 7 h2s, 5 h3s, 7 h4s, 2 h5s defined in this stylesheet." severity="warning"/>
</file>
</csslint>
```

This results in a Jenkins output:

```
Error when parsing /var/lib/jenkins/workspace/xxxxxx/css-results.xml as CSSLINT
java.lang.RuntimeException: "line" not found in "<issue severity="warning" reason="Too many !important declarations (38), try to use less than 10 to avoid specificity issues." evidence=""/>"
	at se.bjurr.violations.lib.parsers.ViolationParserUtils.getAttribute(ViolationParserUtils.java:73)
	at se.bjurr.violations.lib.parsers.ViolationParserUtils.getIntegerAttribute(ViolationParserUtils.java:113)
	at se.bjurr.violations.lib.parsers.CSSLintParser.parseFile(CSSLintParser.java:35)
	at se.bjurr.violations.lib.reports.Reporter.findViolations(Reporter.java:58)
	at se.bjurr.violations.lib.ViolationsReporterApi.violations(ViolationsReporterApi.java:53)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.doPerform(JvctbPerformer.java:66)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:124)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:111)
	at hudson.FilePath.act(FilePath.java:1018)
	at hudson.FilePath.act(FilePath.java:996)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.jvctsPerform(JvctbPerformer.java:111)
	at org.jenkinsci.plugins.jvctb.ViolationsToBitbucketServerRecorder.perform(ViolationsToBitbucketServerRecorder.java:61)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:59)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:52)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tomasbjerre** [comment]
Should be fixed now. Open issue again if not fixed!
