### ISSUE TITLE
JUnit parser throws StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by uhafner** [tomasbjerre/violations-lib#113]
My dependabot PR to bump violations-lib to the latest version (jenkinsci/analysis-model#519) fails with a `java.lang.StringIndexOutOfBoundsException`:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at se.bjurr.violations.lib.parsers.JUnitParser.findFilePathInContent(JUnitParser.java:113)
	at se.bjurr.violations.lib.parsers.JUnitParser.parseFailure(JUnitParser.java:67)
	at se.bjurr.violations.lib.parsers.JUnitParser.parseReportOutput(JUnitParser.java:42)
	at edu.hm.hafner.analysis.parser.violations.AbstractViolationAdapter.parse(AbstractViolationAdapter.java:35)
```

The CI build results are here
https://github.com/jenkinsci/analysis-model/pull/519/checks?check_run_id=1269222404

The XML file that cannot be parsed anymore: [assignment1.xml](https://github.com/jenkinsci/analysis-model/blob/master/src/test/resources/edu/hm/hafner/analysis/parser/violations/assignment1.xml)

**Comment by tomasbjerre** [comment]
Releasing 1.135 with a fix! Thanks for reporting.

**Comment by uhafner** [comment]
Thanks for fixing so fast, my PR jenkinsci/analysis-model#519 is green again now!
