### ISSUE TITLE
Valid Sarif file fails with NullPointerException

### ISSUE THREAD

**Issue by Olstyle** [tomasbjerre/violations-lib#143]
I am trying to convert a sarif report to code climate and get a Nullpointer exception.
The sarif File is this one   
[sarifFile.zip](https://github.com/tomasbjerre/violations-command-line/files/8252282/sarifFile.zip)
and is found to be valid by   
https://sarifweb.azurewebsites.net/Validation   
(though it does not like the exact format of the location uris very much, but I wouldn't expect for violations-command-line to interpret those strings) 

The Log:

```
Given parameters:
-cc, code-climate_report.json, -v, SARIF, C:\projects\STM32\stm32l5_rtos\Tools\Polyspace, .*\.json\.sarif$, SARIF, -show-debug-info

Parsed parameters:
Runner [violations=[[SARIF, C:\projects\STM32\stm32l5_rtos\Tools\Polyspace, .*\.json\.sarif$, SARIF]], minSeverity=INFO, detailLevel=VERBOSE, maxViolations=2147483647, printViolations=true, diffFrom=, diffTo=, diffMinSeverity=INFO, gitRepo=., diffPrintViolations=false, diffMaxViolations=2147483647, diffDetailLevel=VERBOSE, maxReporterColumnWidth=0, maxRuleColumnWidth=10, maxSeverityColumnWidth=0, maxLineColumnWidth=0, maxMessageColumnWidth=50]
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\.git
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\BKS_Rules.xml
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\CheckLicense.ps1
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\code-climate_report.json
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\completeSarif.ps1
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\ForCodevision\ExportConfigToPS.ps1
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\ForCodevision\match.txt
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\ForCodevision\replace.txt
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\out.txt
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\psres.json
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\psres.sarif.json
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\psres2.sarif
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\Readme.md
FINE .*\.json\.sarif$ matches C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\result_line_nr.json.sarif
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\result_line_nr.sarif
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\result_line_nr2.sarif
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\result_list.sarif
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\sarifFile.zip
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\StandardOptions.txt
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\test.txt
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\uploadAndReport.ps1
FINE .*\.json\.sarif$ does not match C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\violations-command-line-1.21.0.jar
INFO Found 1 reports in C:\projects\STM32\stm32l5_rtos\Tools\Polyspace with pattern .*\.json\.sarif$
INFO     - C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\result_line_nr.json.sarif
SEVERE Error when parsing C:\projects\STM32\stm32l5_rtos\Tools\Polyspace\result_line_nr.json.sarif as shadow.se.bjurr.violations.lib.parsers.SarifParser content:
...[see atatchement]
java.lang.NullPointerException: file
	at shadow.se.bjurr.violations.lib.util.Utils.checkNotNull(Utils.java:27)
	at shadow.se.bjurr.violations.lib.model.Violation.<init>(Violation.java:185)
	at shadow.se.bjurr.violations.lib.model.Violation$ViolationBuilder.build(Violation.java:35)
	at shadow.se.bjurr.violations.lib.parsers.SarifParser.parseReportOutput(SarifParser.java:65)
	at shadow.se.bjurr.violations.lib.reports.ViolationsFinder.findViolations(ViolationsFinder.java:35)
	at shadow.se.bjurr.violations.lib.ViolationsApi.violations(ViolationsApi.java:103)
	at se.bjurr.violations.main.Runner.getAllParsedViolations(Runner.java:471)
	at se.bjurr.violations.main.Runner.performTask(Runner.java:323)
	at se.bjurr.violations.main.Runner.main(Runner.java:312)
	at se.bjurr.violations.main.Main.main(Main.java:6)


Violations in repo

Summary
|          |      |      |       |       |
| Reporter | INFO | WARN | ERROR | Total |
|          |      |      |       |       |
+----------+------+------+-------+-------+
|          |      |      |       |       |
|          | 0    | 0    | 0     | 0     |
|          |      |      |       |       |
+----------+------+------+-------+-------+
```

**Comment by tomasbjerre** [comment]
I started fiddling with this. Problem is that the generated parser, used in this library, stores locations in a `set` and that does not preserve order: https://github.com/tomasbjerre/violations-lib/commit/cf261f5436582013efc31b1781c12c462426b257#diff-2dd47979be3d9576ce941b9e3561398131f2afcaa083fc4b9e9f392562d047bdR38

**Comment by tomasbjerre** [comment]
Looks like the set is actually in order and this can be solved. I'll fix it later today.

**Comment by tomasbjerre** [comment]
I made a new release now. Can you try 1.21.1?

**Comment by Olstyle** [comment]
I tried to get it from [Maven](https://search.maven.org/artifact/se.bjurr.gradle/violations-command-line/1.21.1/jar), but I got the exact same error at the exact same line number. Analysis via beyond compare tells me that the SarifParser.class inside is the same as in 1.21.0 .
Looks like the build didn't cover the changes.

**Comment by tomasbjerre** [comment]
Found my mistake. I made a new release now, hopefully works.

**Comment by Olstyle** [comment]
Now it works both in the file offered here and in much bigger result files my projects produces 👍
